version: "3.2"
services:
  web:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    environment:
      - PORT=3000
    expose:
      - 3000
    ports:
      - 3000
    volumes:
      - ../../src:/application
    networks:
      - rtconn
    depends_on:
      - mongo
    command: ["yarn", "start"]

  mongo:
    image: mongo:latest
    networks:
      - rtconn

networks:
  rtconn:

