version: "3"
services:
  jenkins:
    build:
      context: .
      args:
        DOCKER_GID: ${DOCKER_GID} #export DOCKER_GID=$(cat /etc/group | grep docker | cut -d: -f3)
        DOCKER_ENGINE: ${DOCKER_ENGINE}
        DOCKER_COMPOSE: ${DOCKER_COMPOSE}
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"

volumes:
  jenkins_home:
    external: true
