FROM node:8.9.4-alpine

LABEL maintainer="Don Peter C. Atunalu <patunalu@yahoo.com>" \
      description="This is a NodeJs image that is based on the official nodejs alpine image"
#Install bash
RUN apk add --no-cache \
           bash
CMD ["node"]





