# Set nginx base image
FROM nginx:1.13-alpine

# Image Author / Maintainer
LABEL maintainer="Don Peter C. Atunalu <patunalu@yahoo.com>"

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf
