version: "3.2"
services:
  app:
    image: patunalu/rtconn
    environment:
      - PORT=8080
    networks:
      - rtconn
    depends_on:
      - mongo
      - redis
  nginx:
    image: patunalu/rtconn-nginx:latest
    networks:
      - rtconn
    ports:
      - 8080:80
    depends_on:
      - app

  test:
    image: patunalu/rtconn-spec
    environment:
      - JUNIT_REPORT_PATH=/reports/acceptance.xml
      - PORT=80
      - URL=http://nginx
    networks:
      - rtconn
    depends_on:
      - nginx

  mongo:
    image: mongo:latest
    networks:
      - rtconn
  redis:
    image: redis:latest
    networks:
      - rtconn


networks:
  rtconn:

